name: PlayerInfo
version: 2.0.3
author: Matthww
api: [3.0.0]
description: Shows info about a certain player!
main: Matthww\PlayerInfo\PlayerInfo

commands:
 playerinfo:
  description: show info about a certain player
  usage: "/playerinfo <player>"
  permission: playerinfo.use
  aliases: ['pinfo']
permissions:
  playerinfo:
    default: false
    children:
      playerinfo.use:
        default: op
        description: ""
