name: PlayerInfo
version: 1.0.0
author: Matthww
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
description: Shows info about a certain player!
main: Matthww\PlayerInfo\PlayerInfo

commands:
 playerinfo:
  description: Show info about a certain player!
  usage: "/playerinfo <player>"
  permission: playerinfo.command.use
 pinfo:
  description: Show info about a certain player!
  usage: "/pinfo <player>"
  permission: playerinfo.command.use
permissions:
 playerinfo.command.use:
  description: "Allows the user to run the playerinfo command"
  default: op
